[package]
name = "seeker"
version = "0.1.0"
edition = "2021"
authors = ["Jan M. D. Hansen"]
license-file = "LICENSE"
repository = "https://github.com/jamadaha/seeker"
description = "A PDDL planner"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
serde = { version = "1.0.192", features = ["derive"] }
humantime = "2.1.0"
pddllib = "0.1.2"
indexmap = "2.2.3"
fxhash = "0.2.1"
memory-stats = { version = "1.1.0", features = ["always_use_statm"] }

[profile.release]
debug = 1
